### ISSUE TITLE
The build process breaks double quotes (required by the API Gateway CORS)

### ISSUE THREAD

**Issue by stojanovic** [graphboss/aws-sam-webpack-plugin#37]
I am trying to add CORS for the Serverless API ("AWS::Serverless::Api"). The CORS configuration requires double quotes, for example: `"'https://serverless.pub'"`. However, running the `npm build command`, breaks these double quotes.

## Examples
If I have the following in the template.yaml file:
```yaml
Api:
  Type: AWS::Serverless::Api
  Properties:
    StageName: prod
    Cors:
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
      MaxAge: "'3600'"
      AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"
```

The build command transforms this into:
```yaml
Api:
  Type: 'AWS::Serverless::Api'
  Properties:
    StageName: prod
    Cors:
      AllowHeaders: '''Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'''
      AllowOrigin: '''*'''
      MaxAge: '''3600'''
      AllowMethods: '''OPTIONS,POST,GET,PUT,DELETE'''
```

Inverting these quotes works, but CloudFormation throws an error if I try to build the following example:
```yaml
Api:
  Type: AWS::Serverless::Api
  Properties:
    StageName: prod
    Cors:
      AllowHeaders: '"Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token"'
      AllowOrigin: '"*"'
      MaxAge: '"3600"'
      AllowMethods: '"OPTIONS,POST,GET,PUT,DELETE"'
```

This is the CloudFormation error:
```
[Invalid mapping expression specified: "3600"]
```

Even with the following workaround, the error is the same:
```yaml
MaxAge: "\"3600\""
```
