### ISSUE TITLE
Support for PackageType 'Image

### ISSUE THREAD

**Issue by derdeka** [graphboss/aws-sam-webpack-plugin#47]
AWS recently added a new PackageType `Image`, here is an example:
```yaml
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      # ImageConfig:
        # Uncomment this to override command here from the Dockerfile
        # Command: ["app.lambdaHandler"]
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /hello
            Method: get
    Metadata:
      DockerTag: nodejs12.x-v1
      DockerContext: ./src/hello-world
      Dockerfile: Dockerfile
```

`aws-sam-webpack-plugin` currently does not support image type and throws Error: `Error: HelloWorldFunction has an unsupport Runtime. Must be nodejs10.x or nodejs12.x`
